version: '3'

services:
    chefsbook-webapi:
        container_name: "chefsbook-webapi-container"
        image: chefsbook-webapi-image
        build: 
            context: ./src
            dockerfile: ./Apps/WebApiApp/Dockerfile
        ports:
            - "5001:5001"
        environment:
            ASPNETCORE_URLS: "http://*:5001"
            ASPNETCORE_ENVIRONMENT: "Development"
        links:
            - chefsbook-database

    chefsbook-database:
        container_name: "chefsbook-database-container"
        image: chefsbook-database-image
        build: ./database
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "MyVeryStrongPassword1!"
            ACCEPT_EULA: "Y"