version: '3'

services:
    chefsbook-webapi:
        container_name: "chefsbook-webapi-container"
        image: chefsbook-webapi-image
        build: ./Apps/WebApiApp
        ports:
            - "5000:5000"
        environment:
            ASPNETCORE_URLS: "http://*:5000"
            ASPNETCORE_ENVIRONMENT: "Development"
        links:
            - chefsbook-database

    chefsbook-database:
        container_name: "chefsbook-database-container"
        image: chefsbook-database-image
        build: ./Apps/Database
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "MyVeryStrongPassword1!"
            ACCEPT_EULA: "Y"